apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;
        index index.php index.html;
        server_name _;
        root /var/www/html/public;

        location /app1 {
            proxy_pass http://app1;
        }

        location /app2 {
            proxy_pass http://app2;
        }
    }
